# Generated by Django 3.2 on 2021-09-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_auto_20210913_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.leveldetail'),
        ),
        migrations.AlterField(
            model_name='leveldetail',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
        ),
    ]
