# Generated by Django 3.2 on 2021-09-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0006_auto_20210913_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.leveldetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leveldetail',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
            preserve_default=False,
        ),
    ]
