# Generated by Django 3.2 on 2021-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0007_auto_20210913_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
    ]
