# Generated by Django 3.2 on 2021-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0008_auto_20210913_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
    ]
