# Generated by Django 3.2 on 2021-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0009_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile Number'),
        ),
    ]
