# Generated by Django 3.2 on 2021-09-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0010_alter_user_mobile_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Local Level'), ('P', 'Province Level')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='level_detail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_mgmt.department', verbose_name='Department'),
        ),
        migrations.DeleteModel(
            name='LevelDetail',
        ),
        migrations.AddField(
            model_name='level',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.leveltype'),
        ),
    ]
