# Generated by Django 3.2 on 2021-09-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0011_auto_20210915_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_mgmt.level'),
        ),
    ]
    class Migration(migrations.Migration):

        dependencies = [
            ('user_mgmt', '0012_user_level'),
        ]

        operations = [
            # Example migration: Add a new BooleanField 'is_active' to User
            migrations.AddField(
                model_name='user',
                name='is_active',
                field=models.BooleanField(default=True),
            ),
        ]
