# Generated by Django 3.2 on 2021-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0012_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
