# Generated by Django 3.2 on 2021-09-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0013_alter_menu_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
