# Generated by Django 3.2 on 2021-09-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0014_auto_20210916_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name']},
        ),
    ]
