# Generated by Django 3.2 on 2021-09-17 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0017_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
        ),
    ]
