# Generated by Django 3.2 on 2021-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0018_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
