# Generated by Django 3.2 on 2021-09-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0019_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
        ),
    ]
