# Generated by Django 3.2 on 2021-09-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0022_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='province_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_level', to='user_mgmt.level', verbose_name='Provience Level'),
        ),
    ]
