# Generated by Django 3.2 on 2021-09-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0023_alter_user_level_add_parent_level_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
    ]
