# Generated by Django 3.2 on 2021-09-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0024_remove_department_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Personal Email'),
        ),
    ]
