# Generated by Django 3.2 on 2021-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0026_auto_20210922_0503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_level_roles',
        ),
        migrations.RemoveField(
            model_name='role',
            name='level',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
