# Generated by Django 3.2 on 2021-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0028_update_level_model_add_code_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
