# Generated by Django 3.2 on 2022-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0029_alter_add_district_code_add_nepali_date_in_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_office_head',
            field=models.BooleanField(default=False),
        ),
    ]
