# Generated by Django 3.2 on 2021-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_survey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
