# Generated by Django 3.2 on 2021-09-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_is_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_created',
            new_name='is_options_created',
        ),
    ]
