# Generated by Django 3.2 on 2021-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_created_question_is_options_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(blank=True, choices=[('C', 'Char'), ('B', 'Boolean'), ('D', 'Date'), ('De', 'Decimal'), ('F', 'File')], max_length=5, null=True, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=150, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(error_messages={'unique': 'Question titles should be unique.'}, max_length=500, unique=True, verbose_name='Title'),
        ),
    ]
