# Generated by Django 3.2 on 2021-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_option_change_for_numerator_and_such_field_other_minor_length_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.CharField(blank=True, choices=[('Num', 'Numerator'), ('Deno', 'Denominator'), ('Per', 'Percentage')], max_length=5, null=True, verbose_name='Option Type'),
        ),
    ]
