# Generated by Django 3.2 on 2021-09-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_option_fix_option_type_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_options_created',
            new_name='has_options',
        ),
    ]
