# Generated by Django 3.2 on 2021-09-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_is_options_created_question_has_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='has_options',
            new_name='is_options_created',
        ),
    ]
