# Generated by Django 3.2 on 2021-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_has_options_question_is_options_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_options_created',
            field=models.BooleanField(default=True),
        ),
    ]
