# Generated by Django 3.2 on 2021-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_question_is_options_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='field_type',
            field=models.CharField(choices=[('C', 'Char'), ('B', 'Boolean'), ('D', 'Date'), ('De', 'Decimal'), ('F', 'File'), ('P', 'Percentage Field')], max_length=2, verbose_name='Field Type'),
        ),
    ]
