# Generated by Django 3.2 on 2021-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_option_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sequence_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sequence id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
