# Generated by Django 3.2 on 2021-09-17 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_alter_question_model_remove_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by_local_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_answer', to='core.localbody'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by_provience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provience_answer', to='core.provincebody'),
        ),
        migrations.AddField(
            model_name='fillsurvey',
            name='local_level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_fill_survey', to='core.localbody'),
        ),
        migrations.AddField(
            model_name='fillsurvey',
            name='provience_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provience_fill_survey', to='core.provincebody'),
        ),
    ]
