# Generated by Django 3.2 on 2021-09-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_question_model_remove_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='option',
            name='field_type',
            field=models.CharField(choices=[('C', 'Char'), ('B', 'Boolean'), ('D', 'Date'), ('De', 'Decimal'), ('F', 'File'), ('P', 'Percentage Field'), ('FY', 'Fiscal Year')], max_length=2, verbose_name='Field Type'),
        ),
    ]
