# Generated by Django 3.2 on 2021-09-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0023_alter_user_level_add_parent_level_field'),
        ('core', '0012_alter_answer_fill_survey_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by_local_level',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_by_provience',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_answer', to='user_mgmt.level'),
        ),
        migrations.AddField(
            model_name='fillsurvey',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_fill_survey', to='user_mgmt.level'),
        ),
    ]
