# Generated by Django 3.2 on 2021-09-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_answer_fillsurvey_add_level_reln'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillsurvey',
            name='local_level_id',
        ),
        migrations.RemoveField(
            model_name='fillsurvey',
            name='provience_id',
        ),
    ]
