# Generated by Django 3.2 on 2021-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_answer_fillsurvey_remove_reln_with_local_province_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='sequence_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Sequence id'),
        ),
    ]
