# Generated by Django 3.2 on 2021-09-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_answer_add_fiscal_year'),
        ('core', '0015_alter_option_add_sequence_id'),
    ]

    operations = [
    ]
