# Generated by Django 3.2 on 2021-09-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210921_0525'),
        ('core', '0016_merge_20210921_0530'),
    ]

    operations = [
    ]
