# Generated by Django 3.2 on 2021-09-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20210921_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='field_type',
            field=models.CharField(choices=[('C', 'Character'), ('B', 'Checkbox'), ('D', 'Date'), ('De', 'Number'), ('F', 'File'), ('P', 'Percentage Field'), ('FY', 'Fiscal Year')], max_length=2, verbose_name='Field Type'),
        ),
    ]
