# Generated by Django 3.2 on 2021-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210926_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycorrection',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Checked')], default='P', max_length=1),
        ),
    ]
