# Generated by Django 3.2 on 2021-09-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_surveycorrection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_level_type',
            field=models.CharField(choices=[('L', 'Local Level'), ('P', 'Province Level')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
