# Generated by Django 3.2 on 2021-09-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210927_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user_level_type',
            new_name='action_level_type',
        ),
    ]
