# Generated by Django 3.2 on 2021-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_user_level_type_activitylog_action_level_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action_level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
