# Generated by Django 3.2 on 2021-09-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_activitylog_action_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
    ]
