# Generated by Django 3.2 on 2021-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_activitylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changed_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
