# Generated by Django 3.2 on 2021-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210928_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_level', models.CharField(max_length=100, null=True)),
                ('action_level', models.CharField(max_length=100, null=True)),
                ('action_level_type', models.CharField(choices=[('L', 'Local Level'), ('P', 'Province Level')], max_length=1, null=True)),
                ('option', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_value', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
