# Generated by Django 3.2 on 2021-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210928_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionactivitylog',
            name='option_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
