# Generated by Django 3.2 on 2021-09-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0027_auto_20210922_0925'),
        ('core', '0029_correctionactivitylog_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='user_mgmt.level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
