# Generated by Django 3.2 on 2021-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycorrection',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
