# Generated by Django 3.2 on 2021-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_surveycorrection_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycorrection',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'Septemeber'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
