# Generated by Django 3.2 on 2021-09-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0027_auto_20210922_0925'),
        ('core', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.level'),
        ),
    ]
