# Generated by Django 3.2 on 2021-09-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_notification_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='fill_survey',
        ),
    ]
