# Generated by Django 3.2 on 2021-09-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_notification_fill_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
