# Generated by Django 3.2 on 2021-10-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='correction_checked',
            field=models.BooleanField(default=False),
        ),
    ]
