# Generated by Django 3.2 on 2021-10-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_notification_correction_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint-files/'),
        ),
    ]
