# Generated by Django 3.2 on 2021-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_complaint_model_add_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'वैशाख'), (2, 'ज्येष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'असोज'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फागुन'), (12, 'चैत्र')], null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='surveycorrection',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'वैशाख'), (2, 'ज्येष्ठ'), (3, 'असार'), (4, 'श्रावण'), (5, 'भदौ'), (6, 'असोज'), (7, 'कार्तिक'), (8, 'मंसिर'), (9, 'पौष'), (10, 'माघ'), (11, 'फागुन'), (12, 'चैत्र')], null=True),
        ),
    ]
