# Generated by Django 3.2 on 2021-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_update_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionactivitylog',
            name='question_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionactivitylog',
            name='question_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
