# Generated by Django 3.2 on 2021-11-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20211005_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('score_obtained', models.FloatField(null=True)),
                ('reason', models.TextField(null=True)),
                ('expected_score', models.FloatField(null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='appraisal_review_request/')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
