# Generated by Django 3.2 on 2021-11-08 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0028_update_level_model_add_code_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_add_model_appraisal_review_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalreviewrequest',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisalreviewrequest',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_review', to='user_mgmt.level'),
        ),
        migrations.AddField(
            model_name='appraisalreviewrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
