# Generated by Django 3.2 on 2021-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_model_appraisal_review_request_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date_bs',
            field=models.CharField(max_length=20, null=True, verbose_name='End Date BS'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='start_date_bs',
            field=models.CharField(max_length=20, null=True, verbose_name='Start Date BS'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
