# Generated by Django 3.2 on 2021-11-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_add_district_code_add_nepali_date_in_fy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='field_type',
            field=models.CharField(choices=[('C', 'Character'), ('B', 'Checkbox'), ('D', 'Date'), ('De', 'Amount'), ('F', 'File'), ('P', 'Percentage Field'), ('FY', 'Fiscal Year')], max_length=2, verbose_name='Field Type'),
        ),
    ]
