# Generated by Django 3.2 on 2021-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_model_Update_FiscalYear_Options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='active_fy',
            field=models.BooleanField(default=False, verbose_name='Active Fiscal Year?'),
        ),
    ]
