# Generated by Django 3.2.13 on 2026-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_active_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycorrection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
