# Generated by Django 3.2.13 on 2026-03-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_question_department_full_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycorrection',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CorrectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='correction-files/')),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.surveycorrection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
